### ISSUE TITLE
enableSeparateBuildPerCPUArchitecture:true after this build failed please check below error   

### ISSUE THREAD

**Issue by rahu431** [HarishJangra/react-native-easy-starter#16]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageRelease'.
> 2 exceptions were raised by workers:
  java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: Failed to create 'C:\Users\rahu4\OneDrive\Documents\TheFoodiee\react-native-easy-starter-master\react-native-easy-starter-master\android\app\build\outputs\apk\release\..\..\..\..\..\release\easy-boiler-1.0.8.apk'
  java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: Failed to create 'C:\Users\rahu4\OneDrive\Documents\TheFoodiee\react-native-easy-starter-master\react-native-easy-starter-master\android\app\build\outputs\apk\release\..\..\..\..\..\release\easy-boiler-1.0.8.apk'

**Comment by HarishJangra** [comment]
You can use app bundle. 
[using this npm script](https://github.com/HarishJangra/react-native-easy-starter/blob/6984b5d853289b9665706cbd3ec3c833008a11ab/package.json#L14)

**Comment by rahu431** [comment]
worked bro thanks
