### ISSUE TITLE
A simple mobile app

### ISSUE THREAD

**Issue by ramandhingra** [HarishJangra/react-native-easy-starter#18]
Hi Harish

I have a small mobile app that I need to develop as soon as possible. Could you pl. help me develop it using this kit? I do not have any contact id / phone where I can reach you out, therefore reaching you out here. My email id is coooolers@gmail.com. Kindly contact me asap.

Thank you

**Comment by ramandhingra** [comment]
I do not have Telegram.. Kindly send me your mobile phone

**Comment by HarishJangra** [comment]
Please reply me on mail thanks

**Comment by ramandhingra** [comment]
What is your email, kindly share

**Comment by ramandhingra** [comment]
Okay I got it. Thanks
