### ISSUE TITLE
Got this issue on windows

### ISSUE THREAD

**Issue by gr8ref** [HarishJangra/react-native-easy-starter#19]
Got this issue on windows, but don't need to downgrade node, need to change some hashes on your project:

\node_modules\metro-config\src\defaults\blacklist.js

var sharedBlacklist = [
  /node_modules[/\\]react[/\\]dist[/\\].*/,
  /website\/node_modules\/.*/,
  /heapCapture\/bundle\.js/,
  /.*\/__tests__\/.*/
];
change to:

var sharedBlacklist = [
  /node_modules[\/\\]react[\/\\]dist[\/\\].*/,
  /website\/node_modules\/.*/,
  /heapCapture\/bundle\.js/,
  /.*\/__tests__\/.*/
];

**Comment by 0muxi0** [comment]
![image](https://user-images.githubusercontent.com/26497065/86078144-09418f00-bac0-11ea-9e70-2d846ae707c9.png)
I updated the lib of react-native-safe-area-context but didn`t  solve the problem

**Comment by HarishJangra** [comment]
this is not an error, only a warning. May be in some future releases they'll fix this.
