### ISSUE TITLE
Error type 3 Error: Activity class {com.easy_boiler.debug/com.easy_boiler.MainActivity} does not exist.

### ISSUE THREAD

**Issue by vonwao** [HarishJangra/react-native-easy-starter#20]
I followed instructions but I got this error.  I wonder how can I solve it? 

Using WIndows 10.

```
BUILD SUCCESSFUL in 4m 32s
154 actionable tasks: 154 executed
info Connecting to the development server...
info Starting the app on "emulator-5554"...
Starting: Intent { cmp=com.easy_boiler.debug/com.easy_boiler.MainActivity }
Error type 3
Error: Activity class {com.easy_boiler.debug/com.easy_boiler.MainActivity} does not exist.

```

**Comment by HarishJangra** [comment]
Please start app using ```yarn run  android:dev```

**Comment by cloudstr21** [comment]
Facing same issue here... but it's only happens when i debug with android phone device and it works when i use android emulator.

**Comment by HarishJangra** [comment]
please check the script in `package.json`. i have edited the correct script
> Please start app using `yarn run android`
