### ISSUE TITLE
CodePush Issue

### ISSUE THREAD

**Issue by rahu431** [HarishJangra/react-native-easy-starter#25]
Hi, I am try to use your starter for my own product development very happy to keep it till now.
I didn't see any code push function wrap on any component like below one, then how it will work?please post a step to configuration for code push.
Sample Code Example: `export default codePush(codePushOptions)(Root);`

**Comment by HarishJangra** [comment]
You can see it here.. this is implemented accordingly..

 https://github.com/HarishJangra/react-native-easy-starter/blob/b4368eae80ed1a93088b7c92cd939ee329e7339a/src/Services/CheckVersion.js#L78

**Comment by rahu431** [comment]
so we don't have to wrap any component like this "export default codePush(codePushOptions)(Root) ", it will work fine if we push app, right?

**Comment by HarishJangra** [comment]
Yes it will work.
