### ISSUE TITLE
Way to reset the store

### ISSUE THREAD

**Issue by JordanProtin** [HarishJangra/react-native-easy-starter#27]
Hi @HarishJangra,

Thank you so much for your great work !
I like this project structure.

But I would like to inform you about a little issue during the **logout** process.
Indeed, after do logout action, I need that the store must be reset.

To achieve this, I do this following within : 

- the **ConfigureStore.js** file, I'v added this following in the _createStore_ : 

```js
setState: action((state, payload) => payload)
```

- the **AppContext.js** file, in __logoutUser_ action : 

```js
const _logoutUser = useCallback(async () => {
    const reset = resetLoginCredentials();

    if (reset) {
      // do logout

      // UPDATE HERE !
      // reset the store
      const initialState = StoreService.getState();
      initialState.auth.appstate = APP_STATE.PUBLIC;
      StoreService.dispatch.setState(initialState);
    }
  }, []);
```

Checks out [this post](https://github.com/ctrlplusb/easy-peasy/issues/146#issuecomment-483564253) for more information.

I don't know if this is the best way to achieve this.
I hope this help somebody !

Bye ! :smile:

**Comment by HarishJangra** [comment]
Well thanks for asking. But i am doing like this in store initialization [here](https://github.com/HarishJangra/react-native-easy-starter/blob/master/src/Store/index.js)

```js
//used for resetting store
let initialState = {};

const createStore = () => {
  apiClient = Api.createApiClient();

  // you can use apiclient as injections in store or like this only
  store = ConfigureStore(
    {
      ...model,
      reset: action(state => ({
        ...initialState,
      })),
    },
    apiClient,
  );
  //set initial state to store's state
  initialState = store.getState();
//....  
return store;
};

// 👇 Kickoff our StoreCreater and store instance

```

**Comment by JordanProtin** [comment]
Oh great, it's a better way like this.
Thank you @HarishJangra !

**Comment by rajinpangkalpundai** [comment]
> Also you can import reset as
> 
> ```js
>  const resetStore = useStoreActions(actions => actions.reset);
> 
> ///and call
> resetStore();
> ```
How can i import this action reset inside checklogin thunk on my Login model?  i've tried yours above, but it returns promise rejection. Any solution?

**Comment by HarishJangra** [comment]
@rajinpangkalpundai  you can get a function `getStoreActions` in thunk [see here](https://easy-peasy.now.sh/docs/api/thunk.html#arguments)
and call it like
`
getStoreActions().reset() //thats all
`

**Comment by rajinpangkalpundai** [comment]
Thank

> @rajinpangkalpundai you can get a function `getStoreActions` in thunk [see here](https://easy-peasy.now.sh/docs/api/thunk.html#arguments)
> and call it like
> `getStoreActions().reset() //thats all`

Thanks for your reply, it worked. now, i got another question, how do i reset states from certain model (not all state) ?

**Comment by HarishJangra** [comment]
You need to check easy-peasy documentation for detailed  information.

> 
> Thanks for your reply, it worked. now, i got another question, how do i reset states from certain model (not all state) ?
