### ISSUE TITLE
Hot reload 

### ISSUE THREAD

**Issue by anhdo9797** [HarishJangra/react-native-easy-starter#29]
![107436286_723129145189219_9086734805332221417_n](https://user-images.githubusercontent.com/60549336/86987135-8905e280-c1bf-11ea-922e-9b08a55c3c44.jpg)

how can I find 'hot reload' in this project.

i want after pressing ctrl+s => refresh

thank you.

**Comment by HarishJangra** [comment]
hot reload has been refreshed with fast refresh in reactnative 0.62. Please read changelog of react-native versions
