### ISSUE TITLE
selected theme resets after reloading app

### ISSUE THREAD

**Issue by iamhaaamed** [HarishJangra/react-native-easy-starter#30]
Hi,
How can I save the selected theme in AsyncStorage so that when the user close and reopens the app the selected theme still showing? like the one implemented for i18n.

**Comment by HarishJangra** [comment]
Yes you can use asyncstorage inside themecontext you can get theme from storage 
At first or default if not available in storage

**Comment by iamhaaamed** [comment]
is this correct?

`import React, {useMemo} from 'react';
import defaultTheme, {nightTheme} from '..';
import useStorage from '../../services/AsyncStorage';

const ThemeContext = React.createContext();

export const ThemeProvider = ({theme, children}) => {
  const [themeObj, changeTheme] = useStorage('@selectedTheme', defaultTheme);

  const setTheme = (t) => {
    changeTheme(t);
  };

  const contextValue = useMemo(
    () => ({
      theme: themeObj,
      changeTheme: (t) => setTheme(t),
      toggleTheme: () => {
        if (themeObj.id === 1) {
          setTheme(nightTheme);
        } else {
          setTheme(defaultTheme);
        }
      },
    }),
    [themeObj, setTheme],
  );

  return (
    <ThemeContext.Provider value={contextValue}>
      {children}
    </ThemeContext.Provider>
  );
};

export default ThemeContext;
`

**Comment by HarishJangra** [comment]
I think so .. just check and log the themeobj returned from storage. You will get to know if the code works

**Comment by HarishJangra** [comment]
You can just put id of theme in storage for easier access and set the object according to id of theme.
