### ISSUE TITLE
NodeJs don't work

### ISSUE THREAD

**Issue by anhdo9797** [HarishJangra/react-native-easy-starter#34]
Hi HarishJangra!

I am having the same problem with nodejs. When I run `yarn android` then my Nodejs auto close, it did my app can't restart

When I run `yarn clean:android` then my app has functioned normally but it takes quite a lot of time. 

Can you help me?

Thanks you

**Comment by HarishJangra** [comment]
Do you start your server using `yarn start` in new terminal?

**Comment by anhdo9797** [comment]
@HarishJangra Perhaps I was flawed, I didn't `yarn start`

PS: I hope you will add CI/CD for this project to be better. I am feeling very hard with it 👍 

Once again I would like to thank !
