### ISSUE TITLE
Unable to resolve module `./debugger-ui/debuggerWorker.aca173c4.js` from ``

### ISSUE THREAD

**Issue by anhdo9797** [HarishJangra/react-native-easy-starter#36]
Hi, 
I'm having problems with debugger-ui, when I debugger with chorm then i recived error.

![image](https://user-images.githubusercontent.com/60549336/102858645-3a8e8c80-445d-11eb-86be-e415974d04ee.png)

and my console 
![image](https://user-images.githubusercontent.com/60549336/102858921-a113aa80-445d-11eb-87af-702db2b74eef.png)

Can you help me ?

**Comment by HarishJangra** [comment]
restart your metro server. And close the dev tab from browser.
