### ISSUE TITLE
Will not compile (iOS) until you add react-native-i18n

### ISSUE THREAD

**Issue by marcvanh** [HarishJangra/react-native-easy-starter#4]
Missing dependency react-native-i18n. Need to be added to package.json.

**Comment by HarishJangra** [comment]
@marcvanh please try to remove the dependency from xcode and then build.. because it was used before .. and after that it is removed

**Comment by marcvanh** [comment]
That worked as well. Thank you.

**Comment by HarishJangra** [comment]
@marcvanh please create a pr if possible
