### ISSUE TITLE
not able to see console.log or console.warn if I use react-native run-android 

### ISSUE THREAD

**Issue by rahu431** [HarishJangra/react-native-easy-starter#6]
# am not able to see console results if I use 

> react-native run-android

 did you disabled it any where?
# after update app name like "test" showing error on 

> yarn run android:dev

Result:
```
BUILD SUCCESSFUL in 19s
179 actionable tasks: 5 executed, 174 up-to-date
info Running C:\Users\rahu4\AppData\Local\Android\Sdk/platform-tools/adb -s emulator-5554 reverse tcp:8081 tcp:8081
info Starting the app on emulator-5554 (C:\Users\rahu4\AppData\Local\Android\Sdk/platform-tools/adb -s emulator-5554 shell am start -n com.test.debug/com.test.MainActivity)...
Starting: Intent { cmp=com.test.debug/com.test.MainActivity }
Error type 3
Error: Activity class {com.test.debug/com.test.MainActivity} does not exist.
```

**Comment by HarishJangra** [comment]
Please check the package name on android/ and the location of mainactivity accordingly

**Comment by rahu431** [comment]
I have the mainactivity in this path: Test\android\app\src\main\java\com\test\MainActivity.java.
Package name all files package name seems to be changed in android folder and let me know anything I have to change in config to see console.log("testing console log") and console.warn("testing console warn").
