### ISSUE TITLE
Seems broken ( cannot build at all )

### ISSUE THREAD

**Issue by VansonLeung** [HarishJangra/react-native-easy-starter#8]
Hi, I have just tried starting up with iOS simulator. It is showing these errors:

1. i18n library error (solved by deleting the missing lib)
2. RCTGeoLocation library error (solved by deleting the missing lib
3. react-native-keychain library missing (solved by installing back react-native-keychain)
4. node_modules/react-native/scripts/.packager.env : No such file or directory (don't know if it will make APP broken or not yet )
5. iOS simulator Red screen - Native module cannot be null. - NativeEventEmitter.js:36:16 (Don't know the cause, unable to fix)

**Comment by HarishJangra** [comment]
Sorry to say i don't have access to mac. so i never debug it on ios. It is working fine on android.
Please go through RN0.60 docs  for setting up in ios 
Please understand  if you make it work a PR is welcome

If you find a solution. A pr is welcome.

**Comment by drtobbyas** [comment]
Can not build on ubuntu 18.04. Spent a whole day trying different fixes for the various problem I come across. Getting fed up. Please help

**Comment by HarishJangra** [comment]
@drtobbyas  what is the problem you are facing..please add error logs etc

**Comment by drtobbyas** [comment]
@HarishJangra This is the error I'm getting
This is my system spec
CPU~Dual core Intel Core i5 M 560 (-MT-MCP-) speed/max~2342/2667 MHz Kernel~4.15.0-54-generic x86_64 Up~1:40 Mem~6686.6/7902.7MB HDD~500.1GB(82.7% used) Procs~284 Client~Shell
Ubuntu 18.04
Lubuntu desktop installed

$ yarn android:dev
yarn run v1.17.3
$ react-native run-android --appIdSuffix debug
info JS server already running.
info Installing the app...

> Configure project :app
WARNING: API 'variantOutput.getPackageApplication()' is obsolete and has been replaced with 'variant.getPackageApplicationProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getPackageApplication(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.

> Task :app:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
29 actionable tasks: 1 executed, 28 up-to-date
/mnt/01D47BE1D8128F20/drtob/goodies/programming/olalomitv/react-native-easy-starter/android/app/src/main/java/com/olalomitv/MainApplication.java:4: error: cannot find symbol
import com.facebook.react.PackageList;
                         ^
  symbol:   class PackageList
  location: package com.facebook.react
/mnt/01D47BE1D8128F20/drtob/goodies/programming/olalomitv/react-native-easy-starter/android/app/src/main/java/com/olalomitv/MainApplication.java:32: error: cannot find symbol
      List<ReactPackage> packages = new PackageList(this).getPackages();
                                        ^
  symbol: class PackageList
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
/mnt/01D47BE1D8128F20/drtob/goodies/programming/olalomitv/react-native-easy-starter/android/app/src/main/java/com/olalomitv/MainApplication.java:4: error: cannot find symbol
import com.facebook.react.PackageList;
                         ^
  symbol:   class PackageList
  location: package com.facebook.react
/mnt/01D47BE1D8128F20/drtob/goodies/programming/olalomitv/react-native-easy-starter/android/app/src/main/java/com/olalomitv/MainApplication.java:32: error: cannot find symbol
      List<ReactPackage> packages = new PackageList(this).getPackages();
                                        ^
  symbol: class PackageList
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s

    at checkExecSyncError (child_process.js:629:11)
    at execFileSync (child_process.js:647:13)
    at runOnAllDevices (/mnt/01D47BE1D8128F20/drtob/goodies/programming/olalomitv/react-native-easy-starter/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:75:39)
    at buildAndRun (/mnt/01D47BE1D8128F20/drtob/goodies/programming/olalomitv/react-native-easy-starter/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:137:41)
    at then.result (/mnt/01D47BE1D8128F20/drtob/goodies/programming/olalomitv/react-native-easy-starter/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:103:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by HarishJangra** [comment]
@drtobbyas  - Please double check your package names in android folder , AndroidManifest.xml , Mainapplication.java etc 
- Run `yarn`
- run `yarn run clean:debug`

**Comment by HarishJangra** [comment]
fixed in new release
